server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name perseus.local _;

	root /var/www/perseus-homepage;
	index index.html;

	location / {
		try_files $uri $uri/ =404;
	}
}
