server {
	listen 80;
	listen [::]:80;
	server_name eepymoonshine.world www.eepymoonshine.world;

	root /var/www/eepymoonshine-public;
	index index.html;

	location / {
		try_files $uri $uri/ =404;
	}
}
